### ISSUE TITLE
Short alternative commands

### ISSUE THREAD

**Issue by svante-jonsson** [linusromland/Velody#21]
/play --> /p
/nowplaying --> /np
etc.

**Comment by linusromland** [comment]
@svante-jonsson will fix. 
Fix it in same file if possible

**Comment by linusromland** [comment]
https://docs.wornoffkeys.com/commands/commands

**Comment by linusromland** [comment]
`hidden: true` on all short alt!

**Comment by linusromland** [comment]
use legacy command instead, wont fix
