### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by svante-jonsson** [linusromland/Velody#42]
## Idea
Search for a song, list of results is returned, user can choose which song to play/add to queue
- `/search <song name>`
- `!search <song name>`

**Comment by linusromland** [comment]
Will be fixed in 2.0, closing for now.

**Comment by svante-jonsson** [comment]
When do you plan on releasing v2? From what I’ve heard you haven’t worked on Velody in a long time. You are letting us all down! 😥
