### ISSUE TITLE
add command for changing AI presenter volume

### ISSUE THREAD

**Issue by superfroggman** [linusromland/Velody#95]

**Comment by superfroggman** [comment]
![Namnlös](https://github.com/linusromland/Velody/assets/49985901/0ff9a199-b161-466f-a4a1-9d743c46baba)

**Comment by linusromland** [comment]
Thank you for submitting this; it is certainly a feature we are actively considering.

**Comment by linusromland** [comment]
3.0 will have the volume more standard and this should not be needed.
